$(document).ready(function() {
    //Mostrar Sección de la Api
    $("#apis").on("change", function() {
        var selectApi = $(this).val();
        if (selectApi == "api-1") {
            $("#api-1").removeClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-2") {
            $("#api-1").addClass("seccapi");
            $("#api-2").removeClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-3") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").removeClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-4") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").removeClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-5") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").removeClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-6") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").removeClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-7") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").removeClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-8") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").removeClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-9") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").removeClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-10") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").removeClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-11") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").removeClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-12") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").removeClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-13") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").removeClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-14") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").removeClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-15") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").removeClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-16") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").removeClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-17") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").removeClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-18") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").removeClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-19") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").removeClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-20") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").removeClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-21") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").removeClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-22") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").removeClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-23") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").removeClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-24") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").removeClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-25") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").removeClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-26") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").removeClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-27") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").removeClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-28") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").removeClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-29") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").removeClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-30") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").removeClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-31") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").removeClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}
        if (selectApi == "api-32") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").removeClass("seccapi");
        } else {}
        if (selectApi == "0") {
            $("#api-1").addClass("seccapi");
            $("#api-2").addClass("seccapi");
            $("#api-3").addClass("seccapi");
            $("#api-4").addClass("seccapi");
            $("#api-5").addClass("seccapi");
            $("#api-6").addClass("seccapi");
            $("#api-7").addClass("seccapi");
            $("#api-8").addClass("seccapi");
            $("#api-9").addClass("seccapi");
            $("#api-10").addClass("seccapi");
            $("#api-11").addClass("seccapi");
            $("#api-12").addClass("seccapi");
            $("#api-13").addClass("seccapi");
            $("#api-14").addClass("seccapi");
            $("#api-15").addClass("seccapi");
            $("#api-16").addClass("seccapi");
            $("#api-17").addClass("seccapi");
            $("#api-18").addClass("seccapi");
            $("#api-19").addClass("seccapi");
            $("#api-20").addClass("seccapi");
            $("#api-21").addClass("seccapi");
            $("#api-22").addClass("seccapi");
            $("#api-23").addClass("seccapi");
            $("#api-24").addClass("seccapi");
            $("#api-25").addClass("seccapi");
            $("#api-26").addClass("seccapi");
            $("#api-27").addClass("seccapi");
            $("#api-28").addClass("seccapi");
            $("#api-29").addClass("seccapi");
            $("#api-30").addClass("seccapi");
            $("#api-31").addClass("seccapi");
            $("#api-32").addClass("seccapi");
        } else {}

    });
    //Este script muestra elementos dentro de los bloques como lo son la descripción o instrucciones de uso.
    //Llama el bloque del acordeón.
    $('.accordion-toggle').on('click', function(event) {
        event.preventDefault();
        // Crea las variables del aordeón
        var accordion = $(this);
        var accordionContent = accordion.next('.description-content');

        // Activa el acordeón realizando una apertura
        accordion.toggleClass("open");
        // toggle accordion content
        accordionContent.slideToggle(250);
        accordionContent.removeClass("description-content");
        accordionContent.addClass("description-content");
    });

    function popitup(url) {
        newwindow = window.open(url, 'name', 'height=200,width=600');
        if (window.focus) { newwindow.focus() }
        return false;
    }
});
document.addEventListener('DOMContentLoaded', function() {
    var checkPageButton = document.getElementById('apis_lib');
    checkPageButton.addEventListener('click', function() {
        chrome.tabs.getSelected(null, function(tab) {
            d = document
            var f = d.createElement('a');
            f.onclick = window.open('api_ml.html', '_blank', 'width=300,height=900', 'titlebar=no', 'status=no', 'location=no', 'left=100', );
            f.href = "#"
            d.body.appendChild(f);
        });
    }, false);
}, false);


document.addEventListener('DOMContentLoaded', function() {
    var checkPageButton = document.getElementById('arbol_deriv');
    checkPageButton.addEventListener('click', function() {
        chrome.tabs.getSelected(null, function(tab) {
            d = document
            var f = d.createElement('a');
            f.onclick = window.open('arbol.html', '_blank', 'width=300,height=500', 'titlebar=no', 'status=no', 'location=no', 'left=100', );
            f.href = "#"
            d.body.appendChild(f);
        });
    }, false);
}, false);

//Asigno el evento "click" del botón para provoar el copiado
document.getElementById('btnCopiar').addEventListener('click', copiarAlPortapapeles);

//Función que lanza el copiado del código
function copiarAlPortapapeles(ev) {
    var codigoACopiar = document.getElementById('textoACopiar'); //Elemento a copiar
    //Debe estar seleccionado en la página para que surta efecto, así que...
    var seleccion = document.createRange(); //Creo una nueva selección vacía
    seleccion.selectNodeContents(codigoACopiar); //incluyo el nodo en la selección
    //Antes de añadir el intervalo de selección a la selección actual, elimino otros que pudieran existir (sino no funciona en Edge)
    window.getSelection().removeAllRanges();
    window.getSelection().addRange(seleccion); //Y la añado a lo seleccionado actualmente
    try {
        var res = document.execCommand('copy'); //Intento el copiado
        if (res)
            exito();
        else
            fracaso();

        mostrarAlerta();
    } catch (ex) {
        excepcion();
    }
    window.getSelection().removeRange(seleccion);
}